### ISSUE TITLE
Putting html into a popup 

### ISSUE THREAD

**Issue by rsandler00** [thedirtyfew/dash-leaflet#1]
Hi, I want to do something very simple: use HTML within the popup text. For example:

```
dl.Marker(id='QQ', position=[56, 9.8], children=[
                dl.Tooltip("Marker tooltip"),
                dl.Popup([
                    html.H1("Marker popup"),
                    html.P("with <b>inline</b> html")
                ])
            ])
```

Notice the use of <b></b> in `html.P` above. Yet this doesnt work and just prints the html markup along with the string. How do I actually get it to interpret it as html?

Thanks!

**Comment by emilhe** [comment]
It is not working because the suggested syntax is not supported by Dash. I guess that the default syntax would be something like,

`html.P(["with ", html.B("inline"), " html"])`

Alternatively, you could use Markdown,

`dcc.Markdown("with **inline** html")`

If you _really_ need raw html, i think this would be the way to go, 

https://github.com/plotly/dash-dangerously-set-inner-html
