### ISSUE TITLE
GeoTIFFOverlay not working

### ISSUE THREAD

**Issue by dSupertramp** [thedirtyfew/dash-leaflet#138]
<i> Hi everyone! </i>
This is my first issue opening!

I'm working with Dash Leaflet, and I need to put a .tiff file on top of the map - however, the image is not showing.
I also asked this question on StackOverflow here:

https://stackoverflow.com/questions/72041359/geotiffoverlay-not-working-not-showing-image-in-dash-leaflet

**Comment by fiastros** [comment]
- check this working example, it  could help you :
https://github.com/thedirtyfew/dash-leaflet/files/5975933/app_Error_Example.zip

- Make sure your rasters CRS are in EPSG:4326. Only EPSG:4326 / WGS84 coordinates are supported currently.  dash_leaflet does not reproject

- It could be an issue with your raster type because not all rasters types/dtypes are supported

**Comment by emilhe** [comment]
Component dropped as part of the `1.0.0` release.
