### ISSUE TITLE
Possibility to have zoom and center as Inputs in dash callback?

### ISSUE THREAD

**Issue by christianwengert** [thedirtyfew/dash-leaflet#32]
This would be very useful in order to store the last view of a user, so that when he comes back we can reset his last position and zoom. 

If I zoom and pan the map, these props also do not seem to get the current value from the map (viewport too), seems to similar to #25

The section ```https://react-leaflet.js.org/docs/en/components: Manipulating the viewport``` states that 

> These changes can be tracked using the move and moveend events, so your component can store the current center and zoom values as the user interacts with the map, and render these updated values so that the state of your component matches the viewport of the map.

I believe all we have to do is to add something like this 
```

 nProps.onViewportChanged = (e) => {
            nProps.setProps({ viewport: e.viewport });
        }

``` 

in the file  the ```src/lib/components/Map.react.js``` (render method):
```
export default class Map extends Component {
    render() {
        const nProps = Object.assign({}, this.props);
        // Bind events.
        nProps.onclick = (e) => {
            nProps.setProps({ click_lat_lng: [e.latlng.lat, e.latlng.lng] });
        }
        nProps.onlocationfound = (e) => {
            nProps.setProps({ location_lat_lon_acc: [e.latlng.lat, e.latlng.lng, e.accuracy] });
        }
        nProps.ondblclick = (e) => {
            nProps.setProps({ dbl_click_lat_lng: [e.latlng.lat, e.latlng.lng] });
        }
        // Render the leaflet component.
        return <LeafletMap {...nProps} />
    }

}




I wanted to try this out myself, but I cannot get dash-leaflet running on my machine?

My steps here were:

1. git clone this repo
2. python3 -m venv venv
3. .venv/activate
4. git install -r requirements.txt
5. npm install -> this fails with ```> dash_leaflet@0.0.19 validate-init /Users/christian/src/dash-leaflet
> python _validate_init.py

Traceback (most recent call last):
  File "_validate_init.py", line 14, in <module>
    components_lib = importlib.import_module(components_package)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/christian/src/dash-leaflet/dash_leaflet/__init__.py", line 10, in <module>
    from ._imports_ import *
ModuleNotFoundError: No module named 'dash_leaflet._imports_'```

**Comment by emilhe** [comment]
Your approach sounds about right. I am currently changing to a new PC, so i can't try out the code just yet, but i believe that this error should just be ignored. As i remember, it will always be there the first time you build the component (i think it's due to a bug in the dash boilerplate code used when i created the component).

**Comment by christianwengert** [comment]
See my pull request #33 which also updates the readme with the necessary steps for contributing :)

**Comment by emilhe** [comment]
I have just made a new release (0.0.20) which includes the suggested feature. Here is a small example,

```
import dash
import dash_leaflet as dl
import dash_html_components as html
import json

from dash.dependencies import Output, Input, State

app = dash.Dash()
app.layout = html.Div([
dl.Map(dl.TileLayer(), style={'width': '1000px', 'height': '500px'}, id="map"),
html.Div(id="output1"), html.Div(id="output2"), html.Div(id="output3")
])

@app.callback(Output("output1", "children"), [Input("map", "zoom")])
def func(viewport):
        print(viewport)
        return json.dumps(viewport)

@app.callback(Output("output2", "children"), [Input("map", "center")])
def func(viewport):
        print(viewport)
        return json.dumps(viewport)

@app.callback(Output("output3", "children"), [Input("map", "viewport")])
def func(viewport):
        print(viewport)
        return json.dumps(viewport)

if __name__ == '__main__':
        app.run_server()
```

The implementation is based partly on you pull request, but with some differences (e.g. i am also targeting the viewport in the update, i haven't included the test file etc.). I am pretty new to pull request, so i am not quite sure if i should accept it now? :)

**Comment by christianwengert** [comment]
Just For your info:
Now it is theoretically possible to have an infinite loop (happened to me today :)
```
@app.callback(Output("map", "zoom"), [Input("map", "viewport")])
def func(viewport):

        return viewport["zoom"]

```

**Comment by emilhe** [comment]
Haha, that is true. I should probably check if the viewport changed before doing the update 😝

**Comment by christianwengert** [comment]
@emilhe This is working perfectly, I guess we could close the issue

**Comment by annunal** [comment]
In order to see something I had to include the zoom level, otherwise the map was not shown.  However  even like this, in my case there is no firing of the callbacks and so nothing is shown in the outputs.  Can you please re-run this old example ?
I need to get the current viewport in a callback.

thanks
Alessandro

`import dash
import dash_leaflet as dl
from dash_leaflet import Map
import dash_leaflet as dl

import dash_html_components as html
import json

from dash.dependencies import Output, Input, State

    
app = dash.Dash()
app.layout = html.Div([
dl.Map(children=dl.TileLayer(), center=[0,0],zoom=5, style={'width': '1000px', 'height': '500px'}, id="map"),

html.Div(id="output1"), html.Div(id="output2"), html.Div(id="output3")
])

@app.callback(Output("output1", "children"), [Input("map", "zoom")])
def func(viewport):
        print(viewport)
        return json.dumps(viewport)

@app.callback(Output("output2", "children"), [Input("map", "center")])
def func(viewport):
        print(viewport)
        return json.dumps(viewport)

@app.callback(Output("output3", "children"), [Input("map", "viewport")])
def func(viewport):
        print(viewport)
        return json.dumps(viewport)

if __name__ == '__main__':
        app.run_server()`
